name: bayes_topic_measures
channels:
  - conda-forge
dependencies:
  - ipykernel
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pymc>=4
  - arviz
  - xarray
  - seaborn
  - numpyro
  - statsmodels
  - jax
  - optuna

